/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_helloNative */

#ifndef _Included_main_java_helloNative
#define _Included_main_java_helloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_helloNative
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_helloNative_hello
  (JNIEnv *, jclass);

/*
 * Class:     main_java_helloNative
 * Method:    printfnum
 * Signature: (IID)I
 */
JNIEXPORT jint JNICALL Java_main_java_helloNative_printfnum
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     main_java_helloNative
 * Method:    arraytest
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_java_helloNative_arraytest
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
